### ISSUE TITLE
cannot save due to python backend mismatch

### ISSUE THREAD

**Issue by ColinGutow** [ColinGutow/notebook#8]
The python backend doesn't recognize WYSIWYGCell as a cell type and thus prevents it from saving, there are likely some problems with the JSON as well but the backend needs to addressed first so the JSON actually runs.

**Comment by gutow** [comment]
I believe pull #9 fixes this. This issue should be closed. However, will still need to fix nbformat downgrading from v5 to v4 format. Opening new issue #10.

**Comment by ColinGutow** [comment]
fixed with recent update
